import os

from PyInstaller.utils.hooks import collect_all

# Version resource generated by build.ps1 (optional).
version_file = "version_info.txt" if os.path.exists("version_info.txt") else None

datas = [("web", "web"), ("assets", "assets")]
binaries = []
hiddenimports = []

# pywebview + WebView2 backend (dlls, pythonnet, etc.)
for pkg in ("webview",):
    d, b, h = collect_all(pkg)
    datas += d
    binaries += b
    hiddenimports += h

a = Analysis(
    ["main.py"],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=["PySide6", "PySide6.QtWidgets", "PySide6.QtCore", "PySide6.QtGui", "tkinter"],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="Loki",
    debug=False,
    strip=False,
    upx=False,
    console=False,
    icon="assets/icon.ico",
    version=version_file,
)
